Finished Acts 8
ThatXliner/acts-project pull request #29
Opened 2022-10-24 00:28 UTC by EvanZhouDev

Finished animations for Acts 8.

Known Issues:
- Formatting doesn't work on some browsers (not fixed, will do later, not the most important right now)

2022-10-30 21:06 UTC, DragonXDev commented
Few things:
1. Some spacing is off with "Peter" and "Saul's Journey"
2. Few issues while scrolling in the drawer; at one point u can scroll and u have to move your mouse to the right side to continue
3. Saul randomly disappears sometimes and doesn't show while scrolling
4. Transitions can be added for the background color change
5. Possibly add an animation of Saul preaching to a group of people

2022-10-30 21:06 UTC, DragonXDev commented on public/assets/styles/acts8_9.css
> +.words6 {
naming conventions...

2022-10-30 22:37 UTC, ThatXliner requested changes
I’m not done but here we have so far

2022-10-31 00:49 UTC, ThatXliner commented
<img width="1677" alt="Screen Shot 2022-10-30 at 5 49 46 PM" src="https://user-images.githubusercontent.com/66848002/198910794-8deb4447-113e-4f88-94a8-06eaed4c5cd3.png">
screwy....

2022-10-31 00:50 UTC, ThatXliner commented
There could also be a transition from black back to white

2022-11-02 00:16 UTC, EvanZhouDev commented on index.html
> +        currentPage: 3,
Fixed!

2022-11-02 00:18 UTC, EvanZhouDev commented
Many of the things you have requested can be resolved with percentages. I will try to implement that.

2022-11-06 02:55 UTC, merged